sign in, forgot pass and register page for login doctor dashboard
SushantBarje/Electronic-Medical-Record pull request #19
Opened 2022-02-10 18:08 UTC by RYM1999

2022-02-11 03:26 UTC, SushantBarje requested changes
Login already created...

2022-02-11 06:33 UTC, RYM1999 reviewed
register page

2022-03-03 11:05 UTC, SushantBarje commented
Please do changes.

2022-03-03 11:05 UTC, SushantBarje commented
fast

2022-07-09 05:21 UTC, closed without merging